glsl_types: use util_snprintf() in glsl_type and get_array_instance
Instead of plain snprintf(). To fix the MSVC build:

  Compiling src\compiler\glsl_types.cpp ...
glsl_types.cpp
src\compiler\glsl_types.cpp(477) : error C3861: 'snprintf': identifier not found
src\compiler\glsl_types.cpp(485) : error C3861: 'snprintf': identifier not found
src\compiler\glsl_types.cpp(486) : error C3861: 'snprintf': identifier not found
src\compiler\glsl_types.cpp(489) : error C3861: 'snprintf': identifier not found
src\compiler\glsl_types.cpp(871) : error C3861: 'snprintf': identifier not found
scons: *** [build\windows-x86-debug\compiler\glsl_types.obj] Error 2
scons: building terminated because of errors.

Signed-off-by: Andres Gomez <agomez@igalia.com>