FIXME: intel/compiler: update validator to account for half-float exec type promotion
FIXME: drop this and instead implement do what was discussed in the review thread

Commit c84ec70b3a72 implemented execution type promotion to 32-bit for
conversions involving half-float registers, which empirical testing suggested
was required, but it did not incorporate this change into the assembly validator
logic. This commits adds that, preventing validation errors like this:

mov(16)  g9<4>B   g3<16,8,2>HF     { align1 1H };
ERROR: Destination stride must be equal to the ratio of the sizes of the
       execution data type to the destination type

Fixes: c84ec70b3a72 "intel/fs: Promote execution type to 32-bit when any half-float conversion is needed."